### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by walkergv** [hmemcpy/SnagitImgur#23]
I started using this plugin everyday to write documentation in markdown. It's a great tool.  Having the imgur URL added into in the clipboard would be awesome. Save me a couple of clicks 100 times a day!

-gw

**Comment by hmemcpy** [comment]
+1 :)

I hear you. Will definitely add!

**Comment by walkergv** [comment]
Thanks, you ave literally saved me at least 5 minutes every single day. Will install this right away!

**Comment by hmemcpy** [comment]
Excellent :) I'm glad you use it, I used it myself daily :)
The new installer is not up yet, I'll try and upload it ASAP.
I made a small popup instead of opening the browser. And the URL is now copied to the clipboard, but I should probably make this an option...

![image](https://cloud.githubusercontent.com/assets/601206/7735287/06c167e6-ff45-11e4-8e7d-e0104c17fed9.png)

**Comment by hmemcpy** [comment]
And it's out! Please try it and let me know what you think!
https://github.com/hmemcpy/SnagitImgur/releases/tag/1.1
